version: '3'
services:
  chatd:
    build: 
      context: .
      dockerfile: ./cmd/chatd/Dockerfile
    command: ./chatd
    ports:
      - "8080:8080"
    depends_on:
      - realtimed
      - mariadb
    links:
      - realtimed
      - mariadb
    environment:
      - ADDRESS=8080
      - WS_HOST=realtimed:7070
      - WS_PATH=/realtime
      - CONNECTION_STRING=root:maria@tcp(mariadb:3308)/prismapptest?charset=utf8&parseTime=true&loc=UTC
    tty: true 
  realtimed:
    build:
      context: .
      dockerfile: ./cmd/chatd/Dockerfile
    command: ./realtimed
    ports:
      - "7070:7070"
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      - CONNECTION_STRING=root:maria@tcp(mariadb:3308)/prismapptest?charset=utf8&parseTime=true&loc=UTC
    tty: true 
  mariadb:
    build: ./docker/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maria
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mariadb/docker-entrypoint-initdb.d/dump.sql:/docker-entrypoint-initdb.d/dump.sql